// Refresh & purge on demand, from bunny.net/docs/scripting/cache/examples (#3).
import { type CodeLine, f, k, p, type Step, s, t } from "@keyframe/kit/code";

export const CACHE_PURGE_CODE: CodeLine[] = [
  { toks: [k("import "), p("* "), k("as "), f("BunnySDK "), k("from "), s('"@bunny.net/edgescript-sdk"'), p(";")] },
  { toks: [] },
  {
    toks: [
      f("BunnySDK"),
      p("."),
      f("net"),
      p("."),
      f("http"),
      p("."),
      f("serve"),
      p("("),
      k("async "),
      p("("),
      t("request"),
      p(") => {"),
    ],
  },
  {
    toks: [
      p("  "),
      k("const "),
      t("url"),
      p(" = "),
      k("new "),
      f("URL"),
      p("("),
      t("request"),
      p("."),
      f("url"),
      p(");"),
    ],
  },
  { toks: [p("  "), k("const "), t("cache"), p(" = "), f("caches"), p("."), f("default"), p(";")] },
  {
    toks: [
      p("  "),
      k("const "),
      t("cacheKey"),
      p(" = "),
      k("new "),
      f("Request"),
      p("("),
      t("url"),
      p("."),
      f("toString"),
      p("(), { "),
      f("method"),
      p(": "),
      s('"GET"'),
      p(" });"),
    ],
  },
  { toks: [] },
  {
    toks: [p("  "), k("if "), p("("), t("request"), p("."), f("method"), p(" === "), s('"POST"'), p(") {")],
  },
  {
    toks: [
      p("    "),
      k("const "),
      t("fresh"),
      p(" = "),
      f("Response"),
      p("."),
      f("json"),
      p("({ "),
      f("at"),
      p(": "),
      f("Date"),
      p("."),
      f("now"),
      p("() }, {"),
    ],
  },
  { toks: [p("      "), f("headers"), p(": { "), s('"Cache-Control"'), p(": "), s('"s-maxage=60"'), p(" },")] },
  { toks: [p("    });")] },
  {
    toks: [
      p("    "),
      k("await "),
      t("cache"),
      p("."),
      f("put"),
      p("("),
      t("cacheKey"),
      p(", "),
      t("fresh"),
      p("."),
      f("clone"),
      p("());"),
    ],
  },
  { toks: [p("    "), k("return "), k("new "), f("Response"), p("("), s('"Cached for 60s"'), p(");")] },
  { toks: [p("  }")] },
  {
    toks: [p("  "), k("if "), p("("), t("request"), p("."), f("method"), p(" === "), s('"GET"'), p(") {")],
  },
  {
    toks: [
      p("    "),
      k("const "),
      t("hit"),
      p(" = "),
      k("await "),
      t("cache"),
      p("."),
      f("match"),
      p("("),
      t("cacheKey"),
      p(");"),
    ],
  },
  {
    toks: [
      p("    "),
      k("return "),
      t("hit"),
      p(" ?? "),
      k("new "),
      f("Response"),
      p("("),
      s('"Nothing cached"'),
      p(", { "),
      f("status"),
      p(": "),
      t("404"),
      p(" });"),
    ],
  },
  { toks: [p("  }")] },
  {
    toks: [p("  "), k("if "), p("("), t("request"), p("."), f("method"), p(" === "), s('"DELETE"'), p(") {")],
  },
  { toks: [p("    "), k("await "), t("cache"), p("."), f("delete"), p("("), t("cacheKey"), p(");")] },
  { toks: [p("    "), k("return "), k("new "), f("Response"), p("("), s('"Purged"'), p(");")] },
  { toks: [p("  }")] },
  { toks: [p("});")] },
];

export const CACHE_PURGE_STEPS: Step[] = [
  {
    range: [3, 5],
    title: "One key, three verbs",
    body: "GET, POST and DELETE all address the same entry, so they all build the same normalised cache key.",
  },
  {
    range: [7, 10],
    title: "Regenerate on POST",
    body: "A POST builds the fresh payload. s-maxage=60 tells the edge how long the new entry stays valid.",
  },
  {
    range: [11, 12],
    title: "Write it to the edge",
    body: "put() stores a clone under your key. The body can only be read once, so the original is yours to return.",
  },
  {
    range: [14, 16],
    title: "Serve on GET",
    body: "A hit comes straight back from cache. With nothing stored yet, match() resolves to undefined, so answer with a 404.",
  },
  {
    range: [18, 20],
    title: "Purge on DELETE",
    body: "delete() drops the entry from this region's cache, and the next GET starts from empty again.",
  },
];

export const CACHE_PURGE_STEP_LEN = 56;
